# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9f7189f9faf11f0771c1ef2f81c42b8d"
name = "The Cart Ninja"
application_url = "https://9b53-103-186-151-132.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks/app_subscriptions_update"

  [[webhooks.subscriptions]]
  topics = [ "app_purchases_one_time/update" ]
  uri = "/webhooks/app_purchases_one_time_update"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
  uri = "/webhooks/compliance"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,write_discounts,write_products"

[auth]
redirect_urls = [
  "https://9b53-103-186-151-132.ngrok-free.app/auth/callback",
  "https://9b53-103-186-151-132.ngrok-free.app/auth/shopify/callback",
  "https://9b53-103-186-151-132.ngrok-free.app/api/auth/callback"
]

[app_proxy]
url = "https://cartdrawer.fly.dev"
prefix = "apps"
subpath = "cart-app"

