// app/routes/api.cart-settings.jsx
import { sampleCoupons } from '../services/api.cart-settings';

// Sample complete app data structure
const SAMPLE_APP_DATA = {
  cartStatus: true,
  previewCartState: 'items',
  selectedTab: 'progress-bar',
  featureStates: {
    progressBarEnabled: true,
    couponSliderEnabled: true,
    upsellEnabled: true,
  },
  progressBarSettings: {
    showOnEmpty: true,
    barBackgroundColor: '#e5e7eb',
    barForegroundColor: '#93D3FF',
    completionText: 'Free shipping unlocked!',
    rewardsCalculation: ['cartTotal'],
    tiers: [
      {
        id: 1,
        rewardType: 'product',
        minValue: 500,
        description: 'Free Shipping',
        titleBeforeAchieving: 'You\'re {COUNT} away from Free Shipping',
        products: ['sp-1', 'sp-2'],
      },
      {
        id: 2,
        rewardType: 'product',
        minValue: 1000,
        description: 'Free Gift',
        titleBeforeAchieving: 'You\'re {COUNT} away from Free Gift',
        products: ['sp-3'],
      },
    ],
  },
  couponSliderSettings: {
    enabled: true,
    sectionSettings: {
      section_title: 'Available offers',
      section_title_color: '#111827',
      section_title_font_size: 14,
      section_title_font_weight: 700,
      section_background_color: '#fef3c7',
      section_padding: 12,
      section_border_radius: 10,
    },
    cardStyleSettings: {
      card_background_color: '#ffffff',
      card_border_color: '#fcd34d',
      card_border_width: 1,
      card_border_radius: 8,
      card_shadow: true,
      card_padding: 10,
      card_gap_between_cards: 8,
    },
    offers: [
      {
        id: 'co-1',
        coupon_code_text: 'SAVE10',
        coupon_code_color: '#111827',
        coupon_code_font_size: 14,
        coupon_code_font_weight: 700,
        coupon_code_letter_spacing: 1,
        description_text: 'Save 10% on orders over ₹500',
        description_color: '#4b5563',
        description_font_size: 12,
        description_font_weight: 500,
        description_line_height: 1.4,
        button_text: 'Copy code',
        button_text_color: '#ffffff',
        button_background_color: '#111827',
        button_font_size: 12,
        button_font_weight: 600,
        button_padding_top_bottom: 6,
        button_padding_left_right: 12,
        button_border_radius: 6,
        button_border_color: '#111827',
        button_border_width: 1,
        show_button: true,
        icon_image_url: 'https://via.placeholder.com/40',
        icon_width: 32,
        icon_height: 32,
        icon_border_radius: 8,
        icon_background_color: '#fef3c7',
        icon_alignment: 'left',
        show_icon: true,
        discount_type: 'percentage',
        discount_value: 10,
        minimum_order_value: 500,
        is_enabled: true,
      },
      {
        id: 'co-2',
        coupon_code_text: 'FLAT75',
        coupon_code_color: '#111827',
        coupon_code_font_size: 14,
        coupon_code_font_weight: 700,
        coupon_code_letter_spacing: 1,
        description_text: 'Flat ₹75 off on your first order',
        description_color: '#4b5563',
        description_font_size: 12,
        description_font_weight: 500,
        description_line_height: 1.4,
        button_text: 'Apply now',
        button_text_color: '#ffffff',
        button_background_color: '#0f172a',
        button_font_size: 12,
        button_font_weight: 600,
        button_padding_top_bottom: 6,
        button_padding_left_right: 12,
        button_border_radius: 6,
        button_border_color: '#0f172a',
        button_border_width: 1,
        show_button: true,
        icon_image_url: 'https://via.placeholder.com/40',
        icon_width: 32,
        icon_height: 32,
        icon_border_radius: 8,
        icon_background_color: '#e0f2fe',
        icon_alignment: 'left',
        show_icon: true,
        discount_type: 'flat',
        discount_value: 75,
        minimum_order_value: 0,
        is_enabled: true,
      },
      {
        id: 'co-3',
        coupon_code_text: 'SHIPFREE',
        coupon_code_color: '#111827',
        coupon_code_font_size: 14,
        coupon_code_font_weight: 700,
        coupon_code_letter_spacing: 1,
        description_text: 'Free shipping above ₹900',
        description_color: '#4b5563',
        description_font_size: 12,
        description_font_weight: 500,
        description_line_height: 1.4,
        button_text: 'Reveal code',
        button_text_color: '#0f172a',
        button_background_color: '#ffffff',
        button_font_size: 12,
        button_font_weight: 600,
        button_padding_top_bottom: 6,
        button_padding_left_right: 12,
        button_border_radius: 6,
        button_border_color: '#0f172a',
        button_border_width: 1,
        show_button: false,
        icon_image_url: 'https://via.placeholder.com/40',
        icon_width: 32,
        icon_height: 32,
        icon_border_radius: 8,
        icon_background_color: '#dcfce7',
        icon_alignment: 'top',
        show_icon: true,
        discount_type: 'flat',
        discount_value: 0,
        minimum_order_value: 900,
        is_enabled: false,
      },
    ],
  },
  upsellSettings: {
    enabled: true,
    products: ['sp-2', 'sp-4', 'sp-6'],
    displayPosition: 'bottom',
    title: 'You might also like',
  },
  cartData: {
    cartValue: 640,
    totalQuantity: 3,
    items: [
      {
        id: 1,
        title: 'Premium T-Shirt',
        price: 320,
        qty: 2,
        image: '👕',
      },
      {
        id: 2,
        title: 'Classic Cap',
        price: 0,
        qty: 1,
        image: '🧢',
      },
    ],
  },
  milestones: {
    amount: [
      {
        id: 'm1',
        type: 'amount',
        target: 500,
        label: '₹500',
        rewardText: 'Free Shipping',
        associatedProducts: ['sp-1'],
      },
      {
        id: 'm2',
        type: 'amount',
        target: 1000,
        label: '₹1000',
        rewardText: 'Free Gift',
        associatedProducts: ['sp-2'],
      },
    ],
    quantity: [
      {
        id: 'qm1',
        type: 'quantity',
        target: 5,
        label: '5 items',
        rewardText: '10% OFF',
        associatedProducts: ['sp-3'],
      },
      {
        id: 'qm2',
        type: 'quantity',
        target: 10,
        label: '10 items',
        rewardText: 'Free Surprise Gift',
        associatedProducts: ['sp-4'],
      },
    ],
  },
  shopifyProducts: [
    {
      id: 'sp-1',
      title: 'Gift Card',
      price: '10.00',
      image: '🎁',
      variants: 4,
      status: 'outofstock',
    },
    {
      id: 'sp-2',
      title: 'The Inventory Not Tracked Snowboard',
      price: '949.95',
      image: '🏂',
      variants: 1,
      status: 'active',
    },
    {
      id: 'sp-3',
      title: 'The Archived Snowboard',
      price: '629.95',
      image: '🏂',
      variants: 1,
      status: 'archived',
    },
    {
      id: 'sp-4',
      title: 'The Draft Snowboard',
      price: '2629.95',
      image: '🏂',
      variants: 1,
      status: 'draft',
    },
    {
      id: 'sp-5',
      title: 'The Out of Stock Snowboard',
      price: '885.95',
      image: '🏂',
      variants: 1,
      status: 'outofstock',
    },
    {
      id: 'sp-6',
      title: 'Premium Hoodie',
      price: '129.99',
      image: '🧥',
      variants: 3,
      status: 'active',
    },
    {
      id: 'sp-7',
      title: 'Classic Jeans',
      price: '89.99',
      image: '👖',
      variants: 5,
      status: 'active',
    },
    {
      id: 'sp-8',
      title: 'Sports Cap',
      price: '39.99',
      image: '🧢',
      variants: 2,
      status: 'active',
    },
  ],
};

// This loader function acts as our GET endpoint for the cart drawer
export async function loader() {
  // Return sample coupons data
  return new Response(JSON.stringify({ coupons: sampleCoupons }), {
    headers: {
      'Content-Type': 'application/json',
      // Add CORS headers to allow the storefront to fetch this
      'Access-Control-Allow-Origin': '*',
    },
  });
}

// This action function is the single endpoint for saving settings
export async function action({ request }) {
  const formData = await request.formData();
  const settings = JSON.parse(formData.get('settings'));
  // Sample data is updated in memory
  return new Response(JSON.stringify({ success: true }), {
    headers: { 'Content-Type': 'application/json' },
  });
}

// Endpoint to get sample data
export async function getSampleData() {
  return new Response(JSON.stringify(SAMPLE_APP_DATA), {
    headers: {
      'Content-Type': 'application/json',
      'Access-Control-Allow-Origin': '*',
    },
  });
}
